### ISSUE TITLE
Question about the pre-trained segmentation model

### ISSUE THREAD

**Issue by MYM181** [IRMVLab/SNI-SLAM#13]
Hi, thanks for your great work!
I'd like to try SNI-SLAM with segmentation results from the pretrained segmentation model. 
l notice that the model is dinov2_replica.pth. Is it a model pretrained on Replica? I'm wondering if it can work on other datasets.
Could you please give me more information about the pretrained models? 
Thanks a lot.

**Comment by zstsandy** [comment]
The `dinov2_replica.pth` is pretrained on the Replica dataset, and other datasets or scenes require further pretraining.

**Comment by shenyehui** [comment]
> Hi, thanks for your great work! I'd like to try SNI-SLAM with segmentation results from the pretrained segmentation model. l notice that the model is dinov2_replica.pth. Is it a model pretrained on Replica? I'm wondering if it can work on other datasets. Could you please give me more information about the pretrained models? Thanks a lot.

Hi, did you test dinov2_replica.pth on Replica for segmentation? The visualization I tested doesn't work well.
