### ISSUE TITLE
Demo generated

### ISSUE THREAD

**Issue by fyzhang2024** [IRMVLab/SNI-SLAM#14]
Thanks to the author for his excellent work. I would like to ask, how was the Demo generated?

**Comment by zstsandy** [comment]
please follow the `Visualizing SNI-SLAM Results` in README for Demo generation

**Comment by fyzhang2024** [comment]
OK, I have solved the problem

**Comment by zsy0817** [comment]
> Please tell me how you modified the code. I really hope to receive your answer.

I changed it to 40 at the beginning, but the result is still only a line track. Please tell me how you modified the code. I really hope to receive your answer.

**Comment by mirpouya** [comment]
Exactly, I have the same issue.
Visualizer only shows a trajectory with camera pose not the map.

![Image](https://github.com/user-attachments/assets/a147c024-6095-495f-b122-62c8f4f0e36f)
