### ISSUE TITLE
demo  map

### ISSUE THREAD

**Issue by zsy0817** [IRMVLab/SNI-SLAM#17]
Hello, my visualization result only has the camera trajectory, but no reconstructed surrounding environment map. How can I get a rendering similar to the 'demo'?

**Comment by zstsandy** [comment]
Please try to follow the `Visualizing SNI-SLAM Results` in README for visualization similar to the 'demo'

**Comment by zsy0817** [comment]
> Please try to follow the `Visualizing SNI-SLAM Results` in README for visualization similar to the 'demo'

I changed it to 40 at the beginning, but the result is still only a line track.

**Comment by zstsandy** [comment]
I updated `visualizer.py` , please refer to the new version.
