### ISSUE TITLE
关于SLAM中Tracking的方法

### ISSUE THREAD

**Issue by BINOFL** [IRMVLab/SNI-SLAM#3]
在你们论文和supplement中都没有提及关于tracking使用的方法，可以描述一下方法、Baseline和Loss计算吗？

**Comment by zstsandy** [comment]
Camera pose is estimated by constructing loss between rendering results and observations. We use weighted sum of sdf loss, depth loss and rgb loss for loss construction. As this is not the main contribution of our work, the tracking part is only briefly described in the main paper.

**Comment by shenyehui** [comment]
> Camera pose is estimated by constructing loss between rendering results and observations. We use weighted sum of sdf loss, depth loss and rgb loss for loss construction. As this is not the main contribution of our work, the tracking part is only briefly described in the main paper.

I still don't quite understand how the camera position estimation and tracking is achieved, can you describe it specifically or provide some references?

**Comment by zstsandy** [comment]
The code is open source now and you can check the details in the code.
