### ISSUE TITLE
No mesh files in output folder

### ISSUE THREAD

**Issue by Jayyy0311** [IRMVLab/SNI-SLAM#5]
Hello,

I'm reaching out for assistance as I've encountered an issue while running
`python3.7 -W ignore run.py configs/Replica/room1.yaml`
After the tracking progress bar indicates completion at 100%, the terminal seems to freeze without any additional output. I've checked the output folder and found that the mesh folder and tracking_vis folder is empty.
![2024-09-10 14-31-29屏幕截图](https://github.com/user-attachments/assets/5d8f7f89-1f01-4ab4-8ebb-eb60a9411223)

**Comment by lizhiteng111** [comment]
Hello, I also encountered this issue. May I ask how you resolved it?

**Comment by Jayyy0311** [comment]
> Hello, I also encountered this issue. May I ask how you resolved it?
Yes, I set the meshing resolution parameter to 0.05, and after running it and waiting for a while, the mesh file appeared as expected. But the tracking_vis folder is still empty. And I've noticed that the command below is not working either.
`python visualizer.py configs/Replica/room1.yaml --output output/Replica/room1 --top_view --save_rendering`

**Comment by zstsandy** [comment]
mesh saving time is relatively long, requiring approximately 10 minutes of waiting. Visualization is saved in mapping_vis folder. Before run `python visualizer.py`, you need to set `mesh_freq` to 40 (or larger) and save mesh at specific frequency while running the code.

**Comment by Andrewuqing** [comment]
> 网片保存时间相对较长，大约需要等待 10 分钟。可视化效果保存在 mapping_vis 文件夹中。在 run 之前，您需要设置为 40（或更大），并在运行代码时以特定频率保存网格。`python visualizer.py``mesh_freq`

Hello, this command has no effect. How should I modify it   python visualizer.py configs/Replica/room1.yaml --output output/Replica/room1 --top_view --save_rendering

**Comment by zstsandy** [comment]
you can set `mesh_freq` to 40 or larger in https://github.com/IRMVLab/SNI-SLAM/blob/3860456545d3cf7b2358dd3c056ef8d5a2623caf/configs/SNI-SLAM.yaml#L50
and rerun `python -W ignore run.py configs/Replica/room1.yaml`, which may take quite a long time to save mesh during mapping process. Then, run `python visualizer.py` for visualization.

**Comment by Tail-19** [comment]
Hello, I encountered similar issue where mesh saving time is too long. I already sat mesh_res to 0.05 and mesh_freq to 40. However, each mesh saving was about 40min.
