### ISSUE TITLE
ModuleNotFoundError: No module named 'dinov2'

### ISSUE THREAD

**Issue by yjtang249** [IRMVLab/SNI-SLAM#7]
Thanks for your excellent work!
In src/networks/dinov2_seg.py, function make_dinov2_model() raises the error "ModuleNotFoundError: No module named 'dinov2'". Could you please provide the solution? Thank you.

**Comment by zstsandy** [comment]
download `seg` file provided in [google drive](https://drive.google.com/drive/u/0/folders/1BCu8bCGKG9HmnLFbyx7DIHI0slgkeo4h) and unzip facebookresearch_dinov2_main.zip
