### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data0/nerf/sni-slam/seg//semantic_classes.pkl'

### ISSUE THREAD

**Issue by Juanita130** [IRMVLab/SNI-SLAM#8]
Hi,
congrats on your excellent work and thanks a lot for releasing the code. 

When I run "python -W ignore run.py configs/Replica/room1.yaml", 
there is a Error:  FileNotFoundError: [Errno 2] No such file or directory: '/data0/nerf/sni-slam/seg//semantic_classes.pkl'
Could you please provide the solution? Thank you.

<img width="331" alt="1" src="https://github.com/user-attachments/assets/83ea6fb3-6848-4dec-92b9-acebe2692678">
<img width="326" alt="2" src="https://github.com/user-attachments/assets/961f46ea-5b13-4f97-9a15-3f1d9566c259">

**Comment by Juanita130** [comment]
<img width="332" alt="3" src="https://github.com/user-attachments/assets/89c441ba-6099-44f9-ae54-a044f4a785e8">
 
When I changed file path, run  "python -W ignore run.py configs/Replica/room1.yaml" meet the same error.

**Comment by Misswcnm** [comment]
你好 大哥 你最后是怎么解决的 我也遇到了这个问题
