### ISSUE TITLE
Error about “python visualizer.py”

### ISSUE THREAD

**Issue by Juanita130** [IRMVLab/SNI-SLAM#9]
Hi,
congrats on your excellent work and thanks a lot for releasing the code.
I meet an error in the part of "Visualizing SNI-SLAM Results", could you please provide the solution? Thank you very much.
I set mesh_freq to 40 and saved mesh at specific frequency，the command “python visualizer.py” is not working as expected, and my result is as below:
<img width="692" alt="5" src="https://github.com/user-attachments/assets/6b139627-4870-4210-ae6e-ebb104086ee8">
<img width="353" alt="4" src="https://github.com/user-attachments/assets/8961e40b-22d8-458e-997f-c293467d8903">

**Comment by zstsandy** [comment]
you can change f'{output}/mesh/{i:05d}_mesh_culled.ply' into f'{output}/mesh/{i:05d}_mesh_sem.ply' in
https://github.com/IRMVLab/SNI-SLAM/blob/661850307d5fb679465bf4f9b83a9f39f3d8f41c/visualizer.py#L70

**Comment by Juanita130** [comment]
Thank you very much！



At 2024-10-13 16:26:33, "zhusiting" ***@***.***> wrote:

you can change f'{output}/mesh/{i:05d}_mesh_culled.ply' into f'{output}/mesh/{i:05d}_mesh_sem.ply' in
https://github.com/IRMVLab/SNI-SLAM/blob/661850307d5fb679465bf4f9b83a9f39f3d8f41c/visualizer.py#L70

**Comment by Juanita130** [comment]
> you can change f'{output}/mesh/{i:05d}_mesh_culled.ply' into f'{output}/mesh/{i:05d}_mesh_sem.ply' in
> 
> https://github.com/IRMVLab/SNI-SLAM/blob/661850307d5fb679465bf4f9b83a9f39f3d8f41c/visualizer.py#L70

Solved，thank you very much!
